import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HomeLayout from "@/components/layoutComponents/HomeLayout/HomeLayout";
import ReduxProvider from "@/redux/Provider";
import { auth } from "@/backend/auth/auth";
import {SessionProvider} from "next-auth/react"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionProvider session={session}>
        <ReduxProvider>
          <HomeLayout>
            {children}
          </HomeLayout>
        </ReduxProvider>
    </SessionProvider>
      </body>
    </html>
  );
}
