name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.17.0]

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GIT_CLIENT_ID: ${{ secrets.GIT_CLIENT_ID }}
      GIT_CLIENT_SECRET: ${{ secrets.GIT_CLIENT_SECRET }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      UPLOADTHING_APP_ID: ${{ secrets.UPLOADTHING_APP_ID }}
      UPLOADTHING_SECRET: ${{ secrets.UPLOADTHING_SECRET }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: create .env file
      run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
    - name: Build Project
      run: yarn build
    - name: Change Directory
      run: cd /home/biyondbytes/biyondblogs/actions-runner/_work/biyondbytes/biyondbytes
    - run: pm2 restart biyondblogs
