# This workflow will do a clean installation of Node.js dependencies, cache them for efficiency, build the source code, and run tests across different Node.js versions.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # Adjust if necessary (e.g., ubuntu-latest for GitHub-hosted runners)

    strategy:
      matrix:
        node-version: [20.5.1]  # Consider adding more versions to test
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Assuming you have a DATABASE_URL secret defined

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Cache npm dependencies for efficiency
      - name: Install dependencies (clean install)
        run: npm ci  # Ensure deterministic installations in CI

     

      # Consider adding a step to build the source code
      - name: Build source code
        run: npm run build  # Replace with your actual build command

